using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseManager : MonoBehaviour
{
    public GameObject pausePanel; // Panel pauzy
    private bool isPaused = false; // Flaga wskazuj젺a, czy gra jest wstrzymana
    private bool hasRestarted = false; // Flaga wskazuj젺a, czy gra zosta쓰 zrestartowana

    // Funkcja s씃찣ca do inicjalizacji komponent雕
    void Start()
    {
        if (pausePanel == null)
        {
            pausePanel = GameObject.Find("PauseMenu"); // Znalezienie panelu pauzy w scenie
            Debug.Log("pausePanel found in Start: " + (pausePanel != null));
        }

        if (pausePanel != null)
        {
            pausePanel.SetActive(false); // Ukrycie panelu pauzy na pocz졊ku
        }

        SceneManager.sceneLoaded += OnSceneLoaded; // Subskrypcja zdarzenia 쓰dowania sceny
    }

    // Funkcja wywo씇wana po za쓰dowaniu nowej sceny
    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        if (pausePanel == null)
        {
            pausePanel = GameObject.Find("PauseMenu"); // Znalezienie panelu pauzy w nowej scenie
            Debug.Log("pausePanel found in OnSceneLoaded: " + (pausePanel != null));
        }

        if (pausePanel != null)
        {
            pausePanel.SetActive(false); // Ukrycie panelu pauzy po za쓰dowaniu sceny
        }

        Time.timeScale = 1f; // Ustawienie normalnej pr師ko띾i czasu

        if (hasRestarted)
        {
            isPaused = false; // Resetowanie flagi pauzy
            hasRestarted = false; // Resetowanie flagi restartu
        }
    }

    // Funkcja s씃찣ca do aktualizacji stanu gry w ka쯗ej klatce
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (isPaused)
            {
                ResumeGame(); // Wznowienie gry
            }
            else
            {
                PauseGame(); // Wstrzymanie gry
            }
        }
    }

    // Funkcja s씃찣ca do wstrzymania gry
    void PauseGame()
    {
        isPaused = true;
        if (pausePanel != null)
        {
            pausePanel.SetActive(true); // Wy랑ietlenie panelu pauzy
        }
        Time.timeScale = 0f; // Zatrzymanie czasu w grze
    }

    // Funkcja s씃찣ca do wznowienia gry
    public void ResumeGame()
    {
        if (pausePanel != null)
        {
            isPaused = false;
            pausePanel.SetActive(false); // Ukrycie panelu pauzy
        }
        Time.timeScale = 1f; // Ustawienie normalnej pr師ko띾i czasu
    }

    // Funkcja s씃찣ca do restartu gry
    public void RestartGame()
    {
        Time.timeScale = 1f; // Ustawienie normalnej pr師ko띾i czasu

        hasRestarted = true; // Ustawienie flagi restartu

        int currentSceneIndex = SceneManager.GetActiveScene().buildIndex;
        SceneManager.LoadScene(currentSceneIndex); // Za쓰dowanie bie찣cej sceny ponownie
        GameManager.Instance.ResetGame(); // Resetowanie stanu gry
    }

    // Funkcja wywo씇wana przy zniszczeniu obiektu
    private void OnDestroy()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded; // Odsubskrybowanie zdarzenia 쓰dowania sceny
    }
}